services:
  - type: web
    name: clinical-case-api
    runtime: python
    region: singapore
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn clinical_case_platform.wsgi:application --bind 0.0.0.0:$PORT"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: clinical_case_platform.settings_production
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        sync: false
      - key: CORS_ALLOWED_ORIGINS
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: clinical-case-db
          property: connectionString
      - key: USE_S3
        value: FALSE

databases:
  - name: clinical-case-db
    databaseName: clinical_case_platform
    user: clinical_case_user
    region: singapore
    plan: free
